spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    jdbc-url: jdbc:h2:mem:testdb
    username: ccp
    password: ccp
    hikari:
      connection-timeout: 20000
      minimum-idle: 2
      maximum-pool-size: 5
      idle-timeout: 10000

  h2:
    console:
      enabled: true

server:
  port: 8080